# versão para o docker-compose
version: "3.9"
# quais são os serviços que vamos precisar rodar
services:
  database_finapi:
    image: postgres
    container_name: database_finapi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: app_fin_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_finapi
    depends_on:
      - database_finapi



volumes:
  pgdata:
    driver: local
